name : Hola mundo

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    hola:
        runs-on: ubuntu-latest
        steps: 
            - name: saludar
              run: echo "Hola mundo!"
            - name: descargar codigo
              uses: actions/checkout@v3
            - name: En que carpeta estoy?
              run: pwd
            - name: listar archivos
              run: ls -la
            - name: instalar node
              uses: actions/setup-node@v3

            -  name: node version
               run: node --version

            - name: verify npm
              run: npm --version

            - name: start project with package json
              run: npm init -y

            - name: install eslint
              run: npm install --save-dev eslint@eslint/js globals